include: ["_pages"]

kramdown:
  smart_quotes:  ["apos", "apos", "ldquo", "rdquo"]

masthead_title: "ELIXIR Denmark"

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

remote_theme: "mmistakes/minimal-mistakes"
